//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiaOito
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicoPorEspecialidade
    {
        public int Id { get; set; }
        public int MedicoId { get; set; }
        public int EspecialidadeId { get; set; }
    
        public virtual Especialidades Especialidades { get; set; }
        public virtual Medicos Medicos { get; set; }
    }
}
